import { mkdirSync, rmSync } from 'node:fs';
import StyleDictionary from 'style-dictionary';

/**
 * One source of truth, five output layers.
 *
 * Style Dictionary merges every file in a single `source` into ONE token tree
 * keyed by path. That means two files that intentionally reuse the same role
 * names — color.light.json / color.dark.json, density.comfortable.json /
 * density.compact.json — cannot be loaded into the same `source`: the second
 * one silently overwrites the first at every shared path. So each layer below
 * gets its OWN Style Dictionary instance with its own `source`, scoped to just
 * the primitives it needs to resolve references plus the one semantic file it
 * owns. `match` then filters that instance's output down to the tokens that
 * actually belong to the layer (excluding the primitives pulled in only for
 * reference resolution).
 *
 * ORDER IS LOAD-BEARING. Each axis emits its default on ":root" first, then its
 * attribute variants. A root-level attribute then wins on source order, while a
 * nested subtree resolves from its nearest ancestor. Do not reorder.
 */
const LAYERS = [
  {
    name: 'base',
    selector: ':root, :host',
    // primitives + the semantic roles that vary by neither mode nor density
    source: ['tokens/primitive/**/*.json', 'tokens/semantic/dimension.json', 'tokens/semantic/type.json'],
    match: () => true,
  },
  {
    name: 'mode-light',
    selector: ':root, [data-hmha-mode="light"]',
    source: ['tokens/primitive/color.json', 'tokens/semantic/color.light.json'],
    match: (p) => /color\.light/.test(p),
  },
  {
    name: 'mode-dark',
    selector: '[data-hmha-mode="dark"]',
    source: ['tokens/primitive/color.json', 'tokens/semantic/color.dark.json'],
    match: (p) => /color\.dark/.test(p),
  },
  {
    name: 'density-comfortable',
    selector: ':root, [data-hmha-density="comfortable"]',
    source: ['tokens/primitive/dimension.json', 'tokens/semantic/density.comfortable.json'],
    match: (p) => /density\.comfortable/.test(p),
  },
  {
    name: 'density-compact',
    selector: '[data-hmha-density="compact"]',
    source: ['tokens/primitive/dimension.json', 'tokens/semantic/density.compact.json'],
    match: (p) => /density\.compact/.test(p),
  },
];

const BUILD_PATH = 'libs/tokens/src/lib/';

/** Emits the union types the component library's inputs are checked against. */
StyleDictionary.registerFormat({
  name: 'ts/hmha-types',
  format: ({ dictionary }) => {
    const roles = dictionary.allTokens
      .filter((t) => t.filePath.includes('color.light'))
      .map((t) => t.path[t.path.length - 1]);
    return [
      '// GENERATED by Style Dictionary. Do not edit.',
      '',
      'export type HmhaColorRole =',
      ...roles.map((r) => `  | '${r}'`),
      ';',
      '',
      "export type HmhaMode = 'light' | 'dark';",
      "export type HmhaDensity = 'comfortable' | 'compact';",
      '',
      'export const hmhaColor = (role: HmhaColorRole) => `var(--hmha-color-\${role})`;',
      '',
    ].join('\n');
  },
});

mkdirSync(BUILD_PATH, { recursive: true });
rmSync(BUILD_PATH, { recursive: true, force: true });
mkdirSync(BUILD_PATH, { recursive: true });

for (const layer of LAYERS) {
  const sd = new StyleDictionary({
    source: layer.source,
    // Combining files under one layer's source legitimately re-collides their
    // shared root "$description" metadata; that collision is cosmetic, not a
    // token value, so it is not worth the noise.
    log: { warnings: 'disabled' },
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: 'hmha',
        buildPath: BUILD_PATH,
        files: [
          {
            destination: `_${layer.name}.css`,
            format: 'css/variables',
            filter: (token) => layer.match(token.filePath),
            options: {
              selector: layer.selector,
              // THE critical setting: keep var() references in the output instead of
              // flattening them to literal values. Without it, runtime theming is
              // impossible — see Fork 03.
              outputReferences: true,
              showFileHeader: false,
            },
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

const typesSd = new StyleDictionary({
  source: ['tokens/primitive/color.json', 'tokens/semantic/color.light.json'],
  log: { warnings: 'disabled' },
  platforms: {
    ts: {
      transformGroup: 'js',
      prefix: 'hmha',
      buildPath: BUILD_PATH,
      files: [{ destination: 'hmha-tokens.ts', format: 'ts/hmha-types' }],
    },
  },
});
await typesSd.buildAllPlatforms();
