import StyleDictionary from 'style-dictionary';

/**
 * One source of truth, five output layers.
 *
 * All token files are loaded together so references resolve across tiers, then
 * each platform FILTERS down to the files that belong in its layer. That is the
 * standard way to get selector-scoped output from a single graph.
 *
 * ORDER IS LOAD-BEARING. Each axis emits its default on ":root" first, then its
 * attribute variants. A root-level attribute then wins on source order, while a
 * nested subtree resolves from its nearest ancestor. Do not reorder.
 */
const LAYERS = [
  {
    name: 'base',
    selector: ':root, :host',
    // primitives + the semantic roles that vary by neither mode nor density
    match: (p) => /primitive/.test(p) || /semantic\/(dimension|type)/.test(p),
  },
  { name: 'mode-light',          selector: ':root, [data-ds-mode="light"]',            match: (p) => /color\.light/.test(p) },
  { name: 'mode-dark',           selector: '[data-ds-mode="dark"]',                    match: (p) => /color\.dark/.test(p) },
  { name: 'density-comfortable', selector: ':root, [data-ds-density="comfortable"]',    match: (p) => /density\.comfortable/.test(p) },
  { name: 'density-compact',     selector: '[data-ds-density="compact"]',              match: (p) => /density\.compact/.test(p) },
];

/** Emits the union types the component library's inputs are checked against. */
StyleDictionary.registerFormat({
  name: 'ts/ds-types',
  format: ({ dictionary }) => {
    const roles = dictionary.allTokens
      .filter((t) => t.filePath.includes('color.light'))
      .map((t) => t.path[t.path.length - 1]);
    return [
      '// GENERATED by Style Dictionary. Do not edit.',
      '',
      'export type DsColorRole =',
      ...roles.map((r) => `  | '${r}'`),
      ';',
      '',
      "export type DsMode = 'light' | 'dark';",
      "export type DsDensity = 'comfortable' | 'compact';",
      '',
      'export const dsColor = (role: DsColorRole) => `var(--ds-color-\${role})`;',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens/**/*.json'],
  // DTCG format: $value / $type
  preprocessors: ['tokens-studio'],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: 'ds',
      buildPath: 'libs/tokens/src/lib/',
      files: LAYERS.map((layer) => ({
        destination: `_${layer.name}.css`,
        format: 'css/variables',
        filter: (token) => layer.match(token.filePath),
        options: {
          selector: layer.selector,
          // THE critical setting: keep var() references in the output instead of
          // flattening them to literal values. Without it, runtime theming is
          // impossible — see Fork 03.
          outputReferences: true,
          showFileHeader: false,
        },
      })),
    },
    ts: {
      transformGroup: 'js',
      prefix: 'ds',
      buildPath: 'libs/tokens/src/lib/',
      files: [{ destination: 'ds-tokens.ts', format: 'ts/ds-types' }],
    },
  },
};
