// hmha-tokens — GENERATED by Style Dictionary. Do not edit.
// Source: tokens/**/*.json   Build: npm run tokens

/** Every semantic colour role, both modes guaranteed to define all of them. */
export type HmhaColorRole =
  | 'bg'
  | 'bg-subtle'
  | 'surface'
  | 'surface-raised'
  | 'surface-sunken'
  | 'text'
  | 'text-muted'
  | 'text-subtle'
  | 'text-on-action'
  | 'border'
  | 'border-strong'
  | 'action'
  | 'action-hover'
  | 'action-active'
  | 'action-subtle'
  | 'action-disabled'
  | 'focus'
  | 'danger'
  | 'danger-subtle'
  | 'danger-text'
  | 'text-on-danger'
  | 'warning'
  | 'warning-subtle'
  | 'warning-text'
  | 'text-on-warning'
  | 'success'
  | 'success-subtle'
  | 'success-text'
  | 'text-on-success';

/** Control sizes, derived from the density layer's height roles. */
export type HmhaSize = 'sm' | 'md' | 'lg';

/** Visual tones a component may take. Deleting a tone token breaks the build. */
export type HmhaTone = 'neutral' | 'action' | 'danger' | 'warning' | 'success';

export type HmhaMode = 'light' | 'dark';
export type HmhaDensity = 'comfortable' | 'compact';

export const HMHA_MODES: readonly HmhaMode[] = ['light', 'dark'] as const;
export const HMHA_DENSITIES: readonly HmhaDensity[] = ['comfortable', 'compact'] as const;

/** Typed accessor for a semantic colour role's custom property. */
export const hmhaColor = (role: HmhaColorRole) => `var(--hmha-color-${role})`;
