// ds-tokens — GENERATED by Style Dictionary. Do not edit.
// Source: tokens/**/*.json   Build: npm run tokens

/** Every semantic colour role, both modes guaranteed to define all of them. */
export type DsColorRole =
  | 'bg'
  | 'bg-subtle'
  | 'surface'
  | 'surface-raised'
  | 'surface-sunken'
  | 'text'
  | 'text-muted'
  | 'text-subtle'
  | 'text-on-action'
  | 'border'
  | 'border-strong'
  | 'action'
  | 'action-hover'
  | 'action-active'
  | 'action-subtle'
  | 'action-disabled'
  | 'focus'
  | 'danger'
  | 'danger-subtle'
  | 'danger-text'
  | 'text-on-danger'
  | 'warning'
  | 'warning-subtle'
  | 'warning-text'
  | 'text-on-warning'
  | 'success'
  | 'success-subtle'
  | 'success-text'
  | 'text-on-success';

/** Control sizes, derived from the density layer's height roles. */
export type DsSize = 'sm' | 'md' | 'lg';

/** Visual tones a component may take. Deleting a tone token breaks the build. */
export type DsTone = 'neutral' | 'action' | 'danger' | 'warning' | 'success';

export type DsMode = 'light' | 'dark';
export type DsDensity = 'comfortable' | 'compact';

export const DS_MODES: readonly DsMode[] = ['light', 'dark'] as const;
export const DS_DENSITIES: readonly DsDensity[] = ['comfortable', 'compact'] as const;

/** Typed accessor for a semantic colour role's custom property. */
export const dsColor = (role: DsColorRole) => `var(--ds-color-${role})`;
