// GENERATED by Style Dictionary. Do not edit.

export type HmhaColorRole =
  | 'bg'
  | 'bg-subtle'
  | 'surface'
  | 'surface-raised'
  | 'surface-sunken'
  | 'text'
  | 'text-muted'
  | 'text-subtle'
  | 'text-on-action'
  | 'border'
  | 'border-strong'
  | 'action'
  | 'action-hover'
  | 'action-active'
  | 'action-subtle'
  | 'action-disabled'
  | 'focus'
  | 'danger'
  | 'danger-subtle'
  | 'danger-text'
  | 'text-on-danger'
  | 'warning'
  | 'warning-subtle'
  | 'warning-text'
  | 'text-on-warning'
  | 'success'
  | 'success-subtle'
  | 'success-text'
  | 'text-on-success'
;

export type HmhaMode = 'light' | 'dark';
export type HmhaDensity = 'comfortable' | 'compact';

export const hmhaColor = (role: HmhaColorRole) => `var(--hmha-color-${role})`;
