import type { Preview } from '@storybook/angular-vite';

// Global design-system CSS — generated by `npm run tokens`, gitignored, same
// file the `hmha-ui:test` karma target loads via its own `styles` array.
// Storybook's `storybook`/`build-storybook` targets point at `hmha-ui:build`
// (the ng-packagr library build), which has no global-styles concept — only
// this preview file can inject one for every story.
import '../../tokens/src/lib/_all.css';
import './preview.css';

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },

    a11y: {
      // 'todo' - show a11y violations in the test UI only
      // 'error' - fail CI on a11y violations
      // 'off' - skip a11y checks entirely
      test: 'todo',
    },
  },
};

export default preview;
