/**
 * Generates libs/ui/src/lib/icon/icon-registry.ts from a curated allowlist
 * of Lucide icon names (scripts/icons/allowlist.json — the reviewable source
 * of truth) plus the raw SVG files in the `lucide-static` package.
 *
 * Lucide puts the shared presentation attributes (fill, stroke, stroke-width,
 * linecap/linejoin) on the OUTER <svg>, not on each child. icon.ts's template
 * already carries those same attributes on its wrapping <svg>, so only the
 * inner markup (the <path>/<circle>/... children) needs to be captured here.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ALLOWLIST_PATH = ROOT + 'scripts/icons/allowlist.json';
const ICONS_DIR = ROOT + 'node_modules/lucide-static/icons/';
const OUT_PATH = ROOT + 'libs/ui/src/lib/icon/icon-registry.ts';

const { icons } = JSON.parse(readFileSync(ALLOWLIST_PATH, 'utf8'));

const entries = icons.map((entry) => (typeof entry === 'string' ? { name: entry, source: entry } : entry));

const seen = new Set();
const missing = [];
const registry = [];

for (const { name, source } of entries) {
  if (seen.has(name)) throw new Error(`generate-icons: duplicate icon name "${name}" in allowlist.json`);
  seen.add(name);

  let raw;
  try {
    raw = readFileSync(ICONS_DIR + source + '.svg', 'utf8');
  } catch {
    missing.push(`${name} (source "${source}")`);
    continue;
  }

  const match = raw.replace(/<!--[\s\S]*?-->/g, '').match(/<svg\b[^>]*>([\s\S]*)<\/svg>/i);
  if (!match) throw new Error(`generate-icons: could not parse inner markup for "${source}.svg"`);

  const markup = match[1].trim().replace(/\s+/g, ' ').replace(/\s*\/>/g, ' />');
  registry.push({ name, markup });
}

if (missing.length) {
  throw new Error(
    `generate-icons: ${missing.length} icon(s) not found in lucide-static — check the name or update the allowlist:\n` +
      missing.map((m) => `  - ${m}`).join('\n'),
  );
}

registry.sort((a, b) => a.name.localeCompare(b.name));

const body = registry.map(({ name, markup }) => `  '${name}': '${markup.replace(/'/g, "\\'")}',`).join('\n');

const output = [
  '// GENERATED by scripts/generate-icons.mjs. Do not edit.',
  '// Source: scripts/icons/allowlist.json + lucide-static (https://lucide.dev, ISC licence).',
  '',
  '/**',
  ' * Inner SVG markup only — the shared presentation attributes (fill, stroke,',
  ' * stroke-width, linecap/linejoin) live on the wrapping <svg> in icon.ts.',
  ' */',
  'export const HMHA_ICONS = {',
  body,
  '} as const satisfies Record<string, string>;',
  '',
  'export type HmhaIconName = keyof typeof HMHA_ICONS;',
  '',
].join('\n');

mkdirSync(ROOT + 'libs/ui/src/lib/icon', { recursive: true });
writeFileSync(OUT_PATH, output);

console.log(`✔ generated ${registry.length} icons → libs/ui/src/lib/icon/icon-registry.ts`);
